
/*

 389. Find the Difference
        Easy
        4.7K
        453
        Companies
        You are given two strings s and t.

        String t is generated by random shuffling string s and then add one more letter at a random position.

        Return the letter that was added to t.

        Example 1:
        Input: s = "abcd", t = "abcde"
        Output: "e"
        Explanation: 'e' is the letter that was added.

        Example 2:
        Input: s = "", t = "y"
        Output: "y"

        
 */




package Strings.Easy;

import java.util.Arrays;

public class FindTheDifference {

    static char findTheDifference(String s, String t) {
        
        char[] s1 = s.toCharArray();
        char[] s2 = t.toCharArray();

        Arrays.sort(s1);
        Arrays.sort(s2);

        for(int i=0;i<s1.length;i++){
            if(s1[i]!=s2[i]){
                return s2[i];
            }
        }

        return s2[s2.length-1];
    }

    public static void main(String[] args) {

        String s = "abcd", t = "abcde";

        System.out.println(findTheDifference(s, t));
    }
}
